import type { Metadata } from "next";
import "./globals.scss";
import { Header } from "@/components/header/Header";
import { Footer } from "@/components/footer/Footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="container">
          <Header />
          <div className="content">
            {children}
          </div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
